//#line 2 "/opt/ros/groovy/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the multisense_ros package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __multisense_ros__SL_BM_CMV4000CONFIG_H__
#define __multisense_ros__SL_BM_CMV4000CONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace multisense_ros
{
  class sl_bm_cmv4000ConfigStatics;
  
  class sl_bm_cmv4000Config
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(sl_bm_cmv4000Config &config, const sl_bm_cmv4000Config &max, const sl_bm_cmv4000Config &min) const = 0;
      virtual void calcLevel(uint32_t &level, const sl_bm_cmv4000Config &config1, const sl_bm_cmv4000Config &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, sl_bm_cmv4000Config &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const sl_bm_cmv4000Config &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, sl_bm_cmv4000Config &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const sl_bm_cmv4000Config &config) const = 0;
      virtual void getValue(const sl_bm_cmv4000Config &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T sl_bm_cmv4000Config::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (sl_bm_cmv4000Config::* field);

      virtual void clamp(sl_bm_cmv4000Config &config, const sl_bm_cmv4000Config &max, const sl_bm_cmv4000Config &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const sl_bm_cmv4000Config &config1, const sl_bm_cmv4000Config &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, sl_bm_cmv4000Config &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const sl_bm_cmv4000Config &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, sl_bm_cmv4000Config &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const sl_bm_cmv4000Config &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const sl_bm_cmv4000Config &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, sl_bm_cmv4000Config &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, sl_bm_cmv4000Config &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<sl_bm_cmv4000Config::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(sl_bm_cmv4000Config &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("resolution"==(*i)->name){resolution = boost::any_cast<std::string>(val);}
        if("fps"==(*i)->name){fps = boost::any_cast<double>(val);}
        if("gain"==(*i)->name){gain = boost::any_cast<double>(val);}
        if("auto_exposure"==(*i)->name){auto_exposure = boost::any_cast<bool>(val);}
        if("auto_exposure_max_time"==(*i)->name){auto_exposure_max_time = boost::any_cast<double>(val);}
        if("auto_exposure_decay"==(*i)->name){auto_exposure_decay = boost::any_cast<int>(val);}
        if("auto_exposure_thresh"==(*i)->name){auto_exposure_thresh = boost::any_cast<double>(val);}
        if("exposure_time"==(*i)->name){exposure_time = boost::any_cast<double>(val);}
        if("auto_white_balance"==(*i)->name){auto_white_balance = boost::any_cast<bool>(val);}
        if("auto_white_balance_decay"==(*i)->name){auto_white_balance_decay = boost::any_cast<int>(val);}
        if("auto_white_balance_thresh"==(*i)->name){auto_white_balance_thresh = boost::any_cast<double>(val);}
        if("white_balance_red"==(*i)->name){white_balance_red = boost::any_cast<double>(val);}
        if("white_balance_blue"==(*i)->name){white_balance_blue = boost::any_cast<double>(val);}
        if("lighting"==(*i)->name){lighting = boost::any_cast<bool>(val);}
        if("flash"==(*i)->name){flash = boost::any_cast<bool>(val);}
        if("led_duty_cycle"==(*i)->name){led_duty_cycle = boost::any_cast<double>(val);}
        if("motor_speed"==(*i)->name){motor_speed = boost::any_cast<double>(val);}
        if("network_time_sync"==(*i)->name){network_time_sync = boost::any_cast<bool>(val);}
      }
    }

    std::string resolution;
double fps;
double gain;
bool auto_exposure;
double auto_exposure_max_time;
int auto_exposure_decay;
double auto_exposure_thresh;
double exposure_time;
bool auto_white_balance;
int auto_white_balance_decay;
double auto_white_balance_thresh;
double white_balance_red;
double white_balance_blue;
bool lighting;
bool flash;
double led_duty_cycle;
double motor_speed;
bool network_time_sync;

    bool state;
    std::string name;

    
}groups;



//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string resolution;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double fps;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gain;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool auto_exposure;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double auto_exposure_max_time;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int auto_exposure_decay;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double auto_exposure_thresh;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double exposure_time;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool auto_white_balance;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int auto_white_balance_decay;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double auto_white_balance_thresh;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double white_balance_red;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double white_balance_blue;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool lighting;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool flash;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double led_duty_cycle;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double motor_speed;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool network_time_sync;
//#line 255 "/opt/ros/groovy/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("sl_bm_cmv4000Config::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const sl_bm_cmv4000Config &__max__ = __getMax__();
      const sl_bm_cmv4000Config &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const sl_bm_cmv4000Config &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const sl_bm_cmv4000Config &__getDefault__();
    static const sl_bm_cmv4000Config &__getMax__();
    static const sl_bm_cmv4000Config &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const sl_bm_cmv4000ConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void sl_bm_cmv4000Config::ParamDescription<std::string>::clamp(sl_bm_cmv4000Config &config, const sl_bm_cmv4000Config &max, const sl_bm_cmv4000Config &min) const
  {
    return;
  }

  class sl_bm_cmv4000ConfigStatics
  {
    friend class sl_bm_cmv4000Config;
    
    sl_bm_cmv4000ConfigStatics()
    {
sl_bm_cmv4000Config::GroupDescription<sl_bm_cmv4000Config::DEFAULT, sl_bm_cmv4000Config> Default("Default", "", 0, 0, true, &sl_bm_cmv4000Config::groups);
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.resolution = "";
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.resolution = "";
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.resolution = "1024x1024x128";
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<std::string>("resolution", "str", 0, "sensor resolution", "{'enum_description': 'Available resolution settings', 'enum': [{'srcline': 69, 'description': '1024x1024x128', 'srcfile': '/home/drc/catkin_ws/src/multisense-3.1/multisense_ros/cfg/multisense.cfg', 'cconsttype': 'const char * const', 'value': '1024x1024x128', 'ctype': 'std::string', 'type': 'str', 'name': '1024x1024_128_disparities'}, {'srcline': 70, 'description': '2048x2048x0', 'srcfile': '/home/drc/catkin_ws/src/multisense-3.1/multisense_ros/cfg/multisense.cfg', 'cconsttype': 'const char * const', 'value': '2048x2048x0', 'ctype': 'std::string', 'type': 'str', 'name': '2048x2048_No_disparities'}]}", &sl_bm_cmv4000Config::resolution)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<std::string>("resolution", "str", 0, "sensor resolution", "{'enum_description': 'Available resolution settings', 'enum': [{'srcline': 69, 'description': '1024x1024x128', 'srcfile': '/home/drc/catkin_ws/src/multisense-3.1/multisense_ros/cfg/multisense.cfg', 'cconsttype': 'const char * const', 'value': '1024x1024x128', 'ctype': 'std::string', 'type': 'str', 'name': '1024x1024_128_disparities'}, {'srcline': 70, 'description': '2048x2048x0', 'srcfile': '/home/drc/catkin_ws/src/multisense-3.1/multisense_ros/cfg/multisense.cfg', 'cconsttype': 'const char * const', 'value': '2048x2048x0', 'ctype': 'std::string', 'type': 'str', 'name': '2048x2048_No_disparities'}]}", &sl_bm_cmv4000Config::resolution)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.fps = 1.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.fps = 15.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.fps = 5.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("fps", "double", 0, "FPS", "", &sl_bm_cmv4000Config::fps)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("fps", "double", 0, "FPS", "", &sl_bm_cmv4000Config::fps)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gain = 1.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gain = 8.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gain = 1.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("gain", "double", 0, "sensor gain", "", &sl_bm_cmv4000Config::gain)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("gain", "double", 0, "sensor gain", "", &sl_bm_cmv4000Config::gain)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auto_exposure = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auto_exposure = 1;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auto_exposure = 1;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("auto_exposure", "bool", 0, "AutoExposure", "", &sl_bm_cmv4000Config::auto_exposure)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("auto_exposure", "bool", 0, "AutoExposure", "", &sl_bm_cmv4000Config::auto_exposure)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auto_exposure_max_time = 0.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auto_exposure_max_time = 0.5;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auto_exposure_max_time = 0.5;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("auto_exposure_max_time", "double", 0, "AutoExposureMaxTime", "", &sl_bm_cmv4000Config::auto_exposure_max_time)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("auto_exposure_max_time", "double", 0, "AutoExposureMaxTime", "", &sl_bm_cmv4000Config::auto_exposure_max_time)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auto_exposure_decay = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auto_exposure_decay = 20;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auto_exposure_decay = 7;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<int>("auto_exposure_decay", "int", 0, "AutoExposureDecay", "", &sl_bm_cmv4000Config::auto_exposure_decay)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<int>("auto_exposure_decay", "int", 0, "AutoExposureDecay", "", &sl_bm_cmv4000Config::auto_exposure_decay)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auto_exposure_thresh = 0.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auto_exposure_thresh = 1.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auto_exposure_thresh = 0.75;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("auto_exposure_thresh", "double", 0, "AutoExposureThresh", "", &sl_bm_cmv4000Config::auto_exposure_thresh)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("auto_exposure_thresh", "double", 0, "AutoExposureThresh", "", &sl_bm_cmv4000Config::auto_exposure_thresh)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.exposure_time = 0.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.exposure_time = 0.5;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.exposure_time = 0.025;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("exposure_time", "double", 0, "Exposure", "", &sl_bm_cmv4000Config::exposure_time)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("exposure_time", "double", 0, "Exposure", "", &sl_bm_cmv4000Config::exposure_time)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auto_white_balance = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auto_white_balance = 1;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auto_white_balance = 1;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("auto_white_balance", "bool", 0, "AutoWhiteBalance", "", &sl_bm_cmv4000Config::auto_white_balance)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("auto_white_balance", "bool", 0, "AutoWhiteBalance", "", &sl_bm_cmv4000Config::auto_white_balance)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auto_white_balance_decay = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auto_white_balance_decay = 20;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auto_white_balance_decay = 3;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<int>("auto_white_balance_decay", "int", 0, "AutoWhiteBalanceDecay", "", &sl_bm_cmv4000Config::auto_white_balance_decay)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<int>("auto_white_balance_decay", "int", 0, "AutoWhiteBalanceDecay", "", &sl_bm_cmv4000Config::auto_white_balance_decay)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auto_white_balance_thresh = 0.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auto_white_balance_thresh = 1.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auto_white_balance_thresh = 0.5;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("auto_white_balance_thresh", "double", 0, "AutoWhiteBalanceThresh", "", &sl_bm_cmv4000Config::auto_white_balance_thresh)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("auto_white_balance_thresh", "double", 0, "AutoWhiteBalanceThresh", "", &sl_bm_cmv4000Config::auto_white_balance_thresh)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.white_balance_red = 0.25;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.white_balance_red = 4.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.white_balance_red = 1.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("white_balance_red", "double", 0, "WhiteBalanceScaleRed", "", &sl_bm_cmv4000Config::white_balance_red)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("white_balance_red", "double", 0, "WhiteBalanceScaleRed", "", &sl_bm_cmv4000Config::white_balance_red)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.white_balance_blue = 0.25;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.white_balance_blue = 4.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.white_balance_blue = 1.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("white_balance_blue", "double", 0, "WhiteBalanceScaleBlue", "", &sl_bm_cmv4000Config::white_balance_blue)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("white_balance_blue", "double", 0, "WhiteBalanceScaleBlue", "", &sl_bm_cmv4000Config::white_balance_blue)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lighting = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lighting = 1;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lighting = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("lighting", "bool", 0, "Lighting", "", &sl_bm_cmv4000Config::lighting)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("lighting", "bool", 0, "Lighting", "", &sl_bm_cmv4000Config::lighting)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.flash = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.flash = 1;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.flash = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("flash", "bool", 0, "Flash", "", &sl_bm_cmv4000Config::flash)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("flash", "bool", 0, "Flash", "", &sl_bm_cmv4000Config::flash)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.led_duty_cycle = 0.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.led_duty_cycle = 1.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.led_duty_cycle = 0.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("led_duty_cycle", "double", 0, "DutyCycle", "", &sl_bm_cmv4000Config::led_duty_cycle)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("led_duty_cycle", "double", 0, "DutyCycle", "", &sl_bm_cmv4000Config::led_duty_cycle)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.motor_speed = 0.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.motor_speed = 5.2;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.motor_speed = 0.0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("motor_speed", "double", 0, "MotorSpeed", "", &sl_bm_cmv4000Config::motor_speed)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<double>("motor_speed", "double", 0, "MotorSpeed", "", &sl_bm_cmv4000Config::motor_speed)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.network_time_sync = 0;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.network_time_sync = 1;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.network_time_sync = 1;
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("network_time_sync", "bool", 0, "NetworkTimeSynchronization", "", &sl_bm_cmv4000Config::network_time_sync)));
//#line 260 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr(new sl_bm_cmv4000Config::ParamDescription<bool>("network_time_sync", "bool", 0, "NetworkTimeSynchronization", "", &sl_bm_cmv4000Config::network_time_sync)));
//#line 231 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 231 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(sl_bm_cmv4000Config::AbstractGroupDescriptionConstPtr(new sl_bm_cmv4000Config::GroupDescription<sl_bm_cmv4000Config::DEFAULT, sl_bm_cmv4000Config>(Default)));
//#line 390 "/opt/ros/groovy/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
    
      for (std::vector<sl_bm_cmv4000Config::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<sl_bm_cmv4000Config::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    sl_bm_cmv4000Config __max__;
    sl_bm_cmv4000Config __min__;
    sl_bm_cmv4000Config __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const sl_bm_cmv4000ConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static sl_bm_cmv4000ConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &sl_bm_cmv4000Config::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const sl_bm_cmv4000Config &sl_bm_cmv4000Config::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const sl_bm_cmv4000Config &sl_bm_cmv4000Config::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const sl_bm_cmv4000Config &sl_bm_cmv4000Config::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<sl_bm_cmv4000Config::AbstractParamDescriptionConstPtr> &sl_bm_cmv4000Config::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<sl_bm_cmv4000Config::AbstractGroupDescriptionConstPtr> &sl_bm_cmv4000Config::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const sl_bm_cmv4000ConfigStatics *sl_bm_cmv4000Config::__get_statics__()
  {
    const static sl_bm_cmv4000ConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = sl_bm_cmv4000ConfigStatics::get_instance();
    
    return statics;
  }

//#line 69 "/home/drc/catkin_ws/src/multisense-3.1/multisense_ros/cfg/multisense.cfg"
      const char * const sl_bm_cmv4000_1024x1024_128_disparities = "1024x1024x128";
//#line 70 "/home/drc/catkin_ws/src/multisense-3.1/multisense_ros/cfg/multisense.cfg"
      const char * const sl_bm_cmv4000_2048x2048_No_disparities = "2048x2048x0";
}

#endif // __SL_BM_CMV4000RECONFIGURATOR_H__
